// Complete mapping of all countries to their ISO 2-letter codes and regions
export const COUNTRY_DATA: Record<string, { code: string; region: string }> = {
	'Afghanistan': { code: 'AF', region: 'asia' },
	'Albania': { code: 'AL', region: 'europe' },
	'Algeria': { code: 'DZ', region: 'africa' },
	'Andorra': { code: 'AD', region: 'europe' },
	'Angola': { code: 'AO', region: 'africa' },
	'Antigua and Barbuda': { code: 'AG', region: 'north_america' },
	'Argentina': { code: 'AR', region: 'south_america' },
	'Armenia': { code: 'AM', region: 'asia' },
	'Australia': { code: 'AU', region: 'oceania' },
	'Austria': { code: 'AT', region: 'europe' },
	'Azerbaijan': { code: 'AZ', region: 'asia' },
	'Bahamas': { code: 'BS', region: 'north_america' },
	'Bahrain': { code: 'BH', region: 'asia' },
	'Bangladesh': { code: 'BD', region: 'asia' },
	'Barbados': { code: 'BB', region: 'north_america' },
	'Belarus': { code: 'BY', region: 'europe' },
	'Belgium': { code: 'BE', region: 'europe' },
	'Belize': { code: 'BZ', region: 'north_america' },
	'Benin': { code: 'BJ', region: 'africa' },
	'Bhutan': { code: 'BT', region: 'asia' },
	'Bolivia': { code: 'BO', region: 'south_america' },
	'Bosnia and Herzegovina': { code: 'BA', region: 'europe' },
	'Botswana': { code: 'BW', region: 'africa' },
	'Brazil': { code: 'BR', region: 'south_america' },
	'Brunei': { code: 'BN', region: 'asia' },
	'Bulgaria': { code: 'BG', region: 'europe' },
	'Burkina Faso': { code: 'BF', region: 'africa' },
	'Burundi': { code: 'BI', region: 'africa' },
	'Cabo Verde': { code: 'CV', region: 'africa' },
	'Cambodia': { code: 'KH', region: 'asia' },
	'Cameroon': { code: 'CM', region: 'africa' },
	'Canada': { code: 'CA', region: 'north_america' },
	'Central African Republic': { code: 'CF', region: 'africa' },
	'Chad': { code: 'TD', region: 'africa' },
	'Chile': { code: 'CL', region: 'south_america' },
	'China': { code: 'CN', region: 'asia' },
	'Colombia': { code: 'CO', region: 'south_america' },
	'Comoros': { code: 'KM', region: 'africa' },
	'Congo': { code: 'CG', region: 'africa' },
	'Costa Rica': { code: 'CR', region: 'north_america' },
	'Croatia': { code: 'HR', region: 'europe' },
	'Cuba': { code: 'CU', region: 'north_america' },
	'Cyprus': { code: 'CY', region: 'europe' },
	'Czech Republic': { code: 'CZ', region: 'europe' },
	'Denmark': { code: 'DK', region: 'europe' },
	'Djibouti': { code: 'DJ', region: 'africa' },
	'Dominica': { code: 'DM', region: 'north_america' },
	'Dominican Republic': { code: 'DO', region: 'north_america' },
	'DR Congo': { code: 'CD', region: 'africa' },
	'Ecuador': { code: 'EC', region: 'south_america' },
	'Egypt': { code: 'EG', region: 'africa' },
	'El Salvador': { code: 'SV', region: 'north_america' },
	'Equatorial Guinea': { code: 'GQ', region: 'africa' },
	'Eritrea': { code: 'ER', region: 'africa' },
	'Estonia': { code: 'EE', region: 'europe' },
	'Eswatini': { code: 'SZ', region: 'africa' },
	'Ethiopia': { code: 'ET', region: 'africa' },
	'Fiji': { code: 'FJ', region: 'oceania' },
	'Finland': { code: 'FI', region: 'europe' },
	'France': { code: 'FR', region: 'europe' },
	'Gabon': { code: 'GA', region: 'africa' },
	'Gambia': { code: 'GM', region: 'africa' },
	'Georgia': { code: 'GE', region: 'asia' },
	'Germany': { code: 'DE', region: 'europe' },
	'Ghana': { code: 'GH', region: 'africa' },
	'Greece': { code: 'GR', region: 'europe' },
	'Grenada': { code: 'GD', region: 'north_america' },
	'Guatemala': { code: 'GT', region: 'north_america' },
	'Guinea': { code: 'GN', region: 'africa' },
	'Guinea-Bissau': { code: 'GW', region: 'africa' },
	'Guyana': { code: 'GY', region: 'south_america' },
	'Haiti': { code: 'HT', region: 'north_america' },
	'Honduras': { code: 'HN', region: 'north_america' },
	'Hong Kong': { code: 'HK', region: 'asia' },
	'Hungary': { code: 'HU', region: 'europe' },
	'Iceland': { code: 'IS', region: 'europe' },
	'India': { code: 'IN', region: 'asia' },
	'Indonesia': { code: 'ID', region: 'asia' },
	'Iran': { code: 'IR', region: 'asia' },
	'Iraq': { code: 'IQ', region: 'asia' },
	'Ireland': { code: 'IE', region: 'europe' },
	'Israel': { code: 'IL', region: 'asia' },
	'Italy': { code: 'IT', region: 'europe' },
	'Ivory Coast': { code: 'CI', region: 'africa' },
	'Jamaica': { code: 'JM', region: 'north_america' },
	'Japan': { code: 'JP', region: 'asia' },
	'Jordan': { code: 'JO', region: 'asia' },
	'Kazakhstan': { code: 'KZ', region: 'asia' },
	'Kenya': { code: 'KE', region: 'africa' },
	'Kiribati': { code: 'KI', region: 'oceania' },
	'Kosovo': { code: 'XK', region: 'europe' },
	'Kuwait': { code: 'KW', region: 'asia' },
	'Kyrgyzstan': { code: 'KG', region: 'asia' },
	'Laos': { code: 'LA', region: 'asia' },
	'Latvia': { code: 'LV', region: 'europe' },
	'Lebanon': { code: 'LB', region: 'asia' },
	'Lesotho': { code: 'LS', region: 'africa' },
	'Liberia': { code: 'LR', region: 'africa' },
	'Libya': { code: 'LY', region: 'africa' },
	'Liechtenstein': { code: 'LI', region: 'europe' },
	'Lithuania': { code: 'LT', region: 'europe' },
	'Luxembourg': { code: 'LU', region: 'europe' },
	'Madagascar': { code: 'MG', region: 'africa' },
	'Malawi': { code: 'MW', region: 'africa' },
	'Malaysia': { code: 'MY', region: 'asia' },
	'Maldives': { code: 'MV', region: 'asia' },
	'Mali': { code: 'ML', region: 'africa' },
	'Malta': { code: 'MT', region: 'europe' },
	'Marshall Islands': { code: 'MH', region: 'oceania' },
	'Mauritania': { code: 'MR', region: 'africa' },
	'Mauritius': { code: 'MU', region: 'africa' },
	'Mexico': { code: 'MX', region: 'north_america' },
	'Micronesia': { code: 'FM', region: 'oceania' },
	'Moldova': { code: 'MD', region: 'europe' },
	'Monaco': { code: 'MC', region: 'europe' },
	'Mongolia': { code: 'MN', region: 'asia' },
	'Montenegro': { code: 'ME', region: 'europe' },
	'Morocco': { code: 'MA', region: 'africa' },
	'Mozambique': { code: 'MZ', region: 'africa' },
	'Myanmar': { code: 'MM', region: 'asia' },
	'Namibia': { code: 'NA', region: 'africa' },
	'Nauru': { code: 'NR', region: 'oceania' },
	'Nepal': { code: 'NP', region: 'asia' },
	'Netherlands': { code: 'NL', region: 'europe' },
	'New Zealand': { code: 'NZ', region: 'oceania' },
	'Nicaragua': { code: 'NI', region: 'north_america' },
	'Niger': { code: 'NE', region: 'africa' },
	'Nigeria': { code: 'NG', region: 'africa' },
	'North Korea': { code: 'KP', region: 'asia' },
	'North Macedonia': { code: 'MK', region: 'europe' },
	'Norway': { code: 'NO', region: 'europe' },
	'Oman': { code: 'OM', region: 'asia' },
	'Pakistan': { code: 'PK', region: 'asia' },
	'Palau': { code: 'PW', region: 'oceania' },
	'Palestine': { code: 'PS', region: 'asia' },
	'Panama': { code: 'PA', region: 'north_america' },
	'Papua New Guinea': { code: 'PG', region: 'oceania' },
	'Paraguay': { code: 'PY', region: 'south_america' },
	'Peru': { code: 'PE', region: 'south_america' },
	'Philippines': { code: 'PH', region: 'asia' },
	'Poland': { code: 'PL', region: 'europe' },
	'Portugal': { code: 'PT', region: 'europe' },
	'Qatar': { code: 'QA', region: 'asia' },
	'Romania': { code: 'RO', region: 'europe' },
	'Russia': { code: 'RU', region: 'europe' },
	'Rwanda': { code: 'RW', region: 'africa' },
	'Saint Kitts and Nevis': { code: 'KN', region: 'north_america' },
	'Saint Lucia': { code: 'LC', region: 'north_america' },
	'Saint Vincent and the Grenadines': { code: 'VC', region: 'north_america' },
	'Samoa': { code: 'WS', region: 'oceania' },
	'San Marino': { code: 'SM', region: 'europe' },
	'Sao Tome and Principe': { code: 'ST', region: 'africa' },
	'Saudi Arabia': { code: 'SA', region: 'asia' },
	'Senegal': { code: 'SN', region: 'africa' },
	'Serbia': { code: 'RS', region: 'europe' },
	'Seychelles': { code: 'SC', region: 'africa' },
	'Sierra Leone': { code: 'SL', region: 'africa' },
	'Singapore': { code: 'SG', region: 'asia' },
	'Slovakia': { code: 'SK', region: 'europe' },
	'Slovenia': { code: 'SI', region: 'europe' },
	'Solomon Islands': { code: 'SB', region: 'oceania' },
	'Somalia': { code: 'SO', region: 'africa' },
	'South Africa': { code: 'ZA', region: 'africa' },
	'South Korea': { code: 'KR', region: 'asia' },
	'South Sudan': { code: 'SS', region: 'africa' },
	'Spain': { code: 'ES', region: 'europe' },
	'Sri Lanka': { code: 'LK', region: 'asia' },
	'Sudan': { code: 'SD', region: 'africa' },
	'Suriname': { code: 'SR', region: 'south_america' },
	'Sweden': { code: 'SE', region: 'europe' },
	'Switzerland': { code: 'CH', region: 'europe' },
	'Syria': { code: 'SY', region: 'asia' },
	'Taiwan': { code: 'TW', region: 'asia' },
	'Tajikistan': { code: 'TJ', region: 'asia' },
	'Tanzania': { code: 'TZ', region: 'africa' },
	'Thailand': { code: 'TH', region: 'asia' },
	'Timor-Leste': { code: 'TL', region: 'asia' },
	'Togo': { code: 'TG', region: 'africa' },
	'Tonga': { code: 'TO', region: 'oceania' },
	'Trinidad and Tobago': { code: 'TT', region: 'north_america' },
	'Tunisia': { code: 'TN', region: 'africa' },
	'Turkey': { code: 'TR', region: 'asia' },
	'Turkmenistan': { code: 'TM', region: 'asia' },
	'Tuvalu': { code: 'TV', region: 'oceania' },
	'Uganda': { code: 'UG', region: 'africa' },
	'Ukraine': { code: 'UA', region: 'europe' },
	'United Arab Emirates': { code: 'AE', region: 'asia' },
	'United Kingdom': { code: 'GB', region: 'europe' },
	'United States': { code: 'US', region: 'north_america' },
	'Uruguay': { code: 'UY', region: 'south_america' },
	'Uzbekistan': { code: 'UZ', region: 'asia' },
	'Vanuatu': { code: 'VU', region: 'oceania' },
	'Vatican City': { code: 'VA', region: 'europe' },
	'Venezuela': { code: 'VE', region: 'south_america' },
	'Vietnam': { code: 'VN', region: 'asia' },
	'Yemen': { code: 'YE', region: 'asia' },
	'Zambia': { code: 'ZM', region: 'africa' },
	'Zimbabwe': { code: 'ZW', region: 'africa' }
};

// Reverse mapping: code -> country name
export const CODE_TO_COUNTRY: Record<string, string> = {};
Object.entries(COUNTRY_DATA).forEach(([country, data]) => {
	CODE_TO_COUNTRY[data.code] = country;
});

// Get country code from name
export function getCountryCode(countryName: string): string {
	return COUNTRY_DATA[countryName]?.code || 'US';
}

// Get region from country name
export function getRegion(countryName: string): string {
	return COUNTRY_DATA[countryName]?.region || 'north_america';
}

// Get country name from code
export function getCountryName(code: string): string {
	return CODE_TO_COUNTRY[code] || '';
}

// Get all country names sorted alphabetically
export function getAllCountries(): string[] {
	return Object.keys(COUNTRY_DATA).sort();
}
